### ISSUE TITLE
おっす

### ISSUE THREAD

**Issue by jsh1n** [ReiSato18/Quantumwalk#1]
おっす

**Comment by jsh1n** [comment]
上のpull requestってやつでmergeできるよ

**Comment by ReiSato18** [comment]
あった

**Comment by jsh1n** [comment]
いえーい

**Comment by jsh1n** [comment]
#2 をmergeしましょう

**Comment by jsh1n** [comment]
まずmasterっていうブランチが本命のやつで, そこからundergraduateっていうブランチつくってそこに書き込んでるよね

**Comment by ReiSato18** [comment]
そうだよ

**Comment by jsh1n** [comment]
それをmasterっていう本命に反映させるのがmergeっていう行為で, それがpull requestっていう上にあるタブからできる

**Comment by jsh1n** [comment]
やってみよー

**Comment by ReiSato18** [comment]
ほお

**Comment by jsh1n** [comment]
#2

**Comment by jsh1n** [comment]
これ押せば俺が出したpull requestっていうmergeしてくださいっていうrequest見れる

**Comment by jsh1n** [comment]
これを管理者のれいが許可すればmergeされる

**Comment by jsh1n** [comment]
mergeされたね

**Comment by jsh1n** [comment]
https://github.com/ReiSato18/Rei/branches
これを見ればここまでのbranchを見れる
